# fly.toml app configuration file generated for nordtek-solutions-as-kunnskapsbase on 2026-04-30T11:15:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nordtek-solutions-as-kunnskapsbase'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
